name: Prerelease
on: workflow_dispatch

jobs:
  publish:
    name: Publish Prerelease
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish to NPM
        uses: actions/setup-node@v4
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - run: npm i
      - run: 'npm version --preid=git --no-git-tag-version 0.0.0-git.$(git rev-parse HEAD)'
      - run: npm publish --provenance --access public --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
